### ISSUE TITLE
Need a way to get stats for a given assignment

### ISSUE THREAD

**Issue by keller91711** [CSGreater-Developers/HMC-Grader#12]
Right now there does not seem to be an easy way to get stats, such as average, median, hi, low from the gradebook. One cannot even scrape for this information, due to the way mouse handling is done plus every grade being over the total (which is redundant information).

**Comment by robojeb** [comment]
I can make the statistics view-able from the problem grading page (which you can get to by clicking the column header for that problem (or from the grader menu in the nav-bar). Though I have some questions regarding this feature:

1. Should this feature be visible to the instructors only?
1. Which statistics should I include: mean, median, hi, low, deviation?

Also I will work on reformatting the gradebook so that the total points is displayed in the header of the column instead of with each submission. I want to leave total points somewhere because not all assignments are out of 100 so it is nice to be able to tell which ones are.

Also a gradebook download is in the works and should be available soon. This will dump all the data in a CSV format that you can work with in excel.
